name: kono
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2    
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.3.0
  rxdart: ^0.28.0
  dartz: ^0.10.1
  uuid: ^4.4.0
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  retrofit: ^4.1.1
  ionicons: ^0.2.2
  logger: ^2.4.0
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  objectbox: ^4.0.3 
  path_provider: ^2.1.4
  convex_bottom_bar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  extended_image: ^9.0.4
  flutter_localization: any
  intl: 0.19.0
  #flip_card: ^0.7.0
  #flip_book: any
  #page_flip: ^0.2.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  retrofit_generator: ^9.1.2
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_verify: ^3.1.0
  go_router_builder: ^2.7.1
  # carousel_slider: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - profiles/local/application_android.yaml
    - profiles/local/application_ios.yaml
    - profiles/local/application_web.yaml  
    - profiles/dev/application_web.yaml  
