import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:kono/ui/page/book_page.dart';
import 'package:kono/ui/screen/book_screen.dart';
import 'package:kono/ui/screen/chapter_screen.dart';
import 'ui/page/home_page.dart';

part 'application_router.g.dart'; // Add this for code generation

// Constants for route paths
const routeBase = '/';
const routeHome = '/home';
const routeChapter = '/chapter';
const routeBook = '/book';

final GlobalKey<NavigatorState> _appNavigatorKey = GlobalKey<NavigatorState>();

// @TypedGoRoute<HomeScreenRoute>(
//   path: routeHome,
// )

// @TypedGoRoute<ChapterScreenRoute>(
//   path: routeChapter,
// )

@TypedGoRoute<BookScreenRoute>(
  path: routeBase,
)

// @immutable
// class HomeScreenRoute extends GoRouteData {
//   const HomeScreenRoute();

//   @override
//   Widget build(BuildContext context, GoRouterState state) {
//     return const HomePage(BookScreen());
//   }
// }


// @immutable
// class ChapterScreenRoute extends GoRouteData {
//   const ChapterScreenRoute();

//   @override
//   Widget build(BuildContext context, GoRouterState state) {
//     return const HomePage(ChapterScreen());
//   }
// }

@immutable
class BookScreenRoute extends GoRouteData {
  const BookScreenRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const HomePage(BookScreen());
  }
}

// @immutable
// class BookPageRoute extends GoRouteData {
//   final String sku;

//   const BookPageRoute({required this.sku});

  

//   @override
//   Widget build(BuildContext context, GoRouterState state) {
//     return  HomePage(BookPage(sku: '',));
//   }
// }

// GoRouter provider setup using TypedGoRoute
final appRouter = Provider<GoRouter>((ref) {
  return GoRouter(
    navigatorKey: _appNavigatorKey,
    initialLocation: routeBase,
    routes: $appRoutes, // Automatically generated by build_runner
    redirect: (context, state) {
      return state.path;
    },
  );
});