import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:kono/ui/page/book_page.dart';
import 'package:kono/ui/screen/book_screen.dart';
import 'package:kono/ui/screen/chapter_screen.dart';
import 'ui/page/home_page.dart';

part 'application_router.g.dart'; // Add this for code generation



final GlobalKey<NavigatorState> _appNavigatorKey = GlobalKey<NavigatorState>();


@TypedGoRoute<BookScreenRoute>(
    path: '/',
    routes: [
      TypedGoRoute<BookPageRoute>(
        path: 'book/:sku',
      ),
            TypedGoRoute<ChapterPageRoute>(
        path: 'chapter/:sectionSku',
      ),
    ]
)


@TypedGoRoute<BookScreenRoute>(
    path: '/',
    routes: [
    
            TypedGoRoute<ChapterPageRoute>(
        path: 'chapter/:sectionSku',
      ),
    ]
)


@immutable
class BookScreenRoute extends GoRouteData {
  const BookScreenRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const HomePage(BookScreen());
  }
}

@immutable
class BookPageRoute extends GoRouteData {
  final String sku;

  const BookPageRoute({required this.sku});

  

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return HomePage(BookPage(sku: sku,));
  }
}

@immutable
class ChapterPageRoute extends GoRouteData {
  final String sectionSku;

  const ChapterPageRoute({required this.sectionSku});

  

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return HomePage(ChapterScreen());
  }
}

final appRouter = Provider<GoRouter>((ref) {
  return GoRouter(
    navigatorKey: _appNavigatorKey,
    routes: $appRoutes, // Automatically generated by build_runner
    redirect: (context, state) {
      return state.path;
    },
  );
});